### ISSUE TITLE
Help understanding how to change the default text

### ISSUE THREAD

**Issue by RyZum** [FakeDomi/DeathTracker#1]
Hi, 

I'm trying this mod and I would like to use the strings $A and $T, but I wasn't able to find out how to change it (the readme indicates either in the mod options in game but I wasn't able to find it or in the config file but there doesn't seem to be a config file in this repo). Could you help me please? 

Thanks !

**Comment by FakeDomi** [comment]
The config file is something that Everest creates when running the mod, I don't know where is (haven't touched the game much since I made this) but it should be somewhere in your Celeste folder.

**Comment by FakeDomi** [comment]
Also, you can change it in-game if you are in the main menu. It just doesn't work once you have a file selected.
